version: '3.1'

services:
  server:
    image: pedrobrasileiro/openface:0.3
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /etc/letsencrypt/live/arroz.cf:/root/openface/tls